language: node_js
node_js:
  - '12'
branches:
  only:
    - master
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: oF98rwN4VXb0Q0CTKC6/phcVPfmMj13MdmyFZJ6jNQy1bLt01WsRl6fFulWyo2BZCGN52RkR8pOIzyriNcx6sdlmt92nypgTvTZSkj0KNyy3DfLjFEK5gKFBMB5EIJ58NLZLBxw92Vwky0GnU/5sJT9WEvF6jwobGlgDcK/C8VMKKS9bVZuDM10OOgFYl5m2w6vVtb4cm2aBP0GEJpfcz9M+1+a4m60NUBOGwgKdK5gR8Zg4l5By47Y6IChtvYTD2esFVAmz/y9Sf2SxBeaATF7j2R/tbNWizWisshWJKOLoxH7g4Jz+Ie/pOpTzpWQDZtqQfaCL28qCdIe+FJIzH6gM/H57NxmmR8xu7cLyVqW7vw+jt8G6wyL/M3tGU78GvuO61HX71JhaZIFq7mfJQ6labsnZU/3zKqomdenzZPWMSgVfICSyURB/66nFp7qTPdQ3FChWq9BCAWDsiMgRW2ml92+j1U8fC0CUVZBEu0Fq/1bYpkTW0sflKAJ3pp8xK1JIwi1C9bcOPQINvcGPAJWR7LF5d/vZal4eAjRBuS9Ze9c7oQxSIV8OhRSqCg9W7r8F/wsdFbDvJoSW6j0Q2gv4SSE9gsRPH9T1ryib/jfgeLc/MHp6DxOEZacf99b231TrBUNTTvXdyn2L71LYl8MQuL5pR+5bPLCTKrMyiMo=
  app: upc-tsw-ef-nest-u201623578
notifications:
  email:
    on_failure: change
    on_success: change
